version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "18:43"
      timezone: "Asia/Shanghai"
    labels:
      - dependencies
      - skip-changelog
    open-pull-requests-limit: 3
