[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "sample"
version = "0.0.1"
dependencies = [
    "requests >= 2.8.1",
]

[project.scripts]
cli-name = "sample.core:hmm"
